### ISSUE TITLE
4k not working 

### ISSUE THREAD

**Issue by gxtham** [mrflashstudio/Quack#14]
I'm not sure if this was on purpose but quack only works on 7k maps for me, it barely works on 4k maps, any tips on how to fix it if there are any?

**Comment by mrflashstudio** [comment]
Barely works? Would be nice if you could provide a video or replay as well as maps you're testing with.

**Comment by gxtham** [comment]
will do in a bit ty for the quick response

**Comment by gxtham** [comment]
heres clip, map in desc. 
https://youtu.be/5cxgtjjUAY0

**Comment by mrflashstudio** [comment]
Fixed in cb7bd9d, new release is out.
