### ISSUE TITLE
"Quack failed to initialize"

### ISSUE THREAD

**Issue by ZenithUDZ** [mrflashstudio/Quack#15]
I opened quack before opening quaver and it responded with this message, I already have net core 3.1 since it opened, Any clue?

Version	10.0.18363 Build 18363
System Type	x64-based PC
Any other information you need: Itoshi teru#7222    (discord)
https://i.imgur.com/ZPOZLC3.png

**Comment by gyarisuta** [comment]
open as administrator
literally

**Comment by ZenithUDZ** [comment]
> open as administrator
> literally

Already tried opening as administrator, Just crashes when opening quaver or trying to press anything.

**Comment by gyarisuta** [comment]
wait does it open a cmd/shell window?

**Comment by ZenithUDZ** [comment]
> wait does it open a cmd/shell window?

Yes it does, It looks if there is an update and than "initializes" and just crashes after
