### ISSUE TITLE
quack not working for me

### ISSUE THREAD

**Issue by bruhbeb** [mrflashstudio/Quack#17]
quack not working i installed desktop runtime but it still doesnt work

**Comment by mrflashstudio** [comment]
very informative

**Comment by lanylow** [comment]
Game had an update. Some offsets are definitely incorrect :)
![image](https://user-images.githubusercontent.com/31806776/121222344-c1f27f80-c886-11eb-835d-6b935e0f4d31.png)

**Comment by lanylow** [comment]
I found the issue, QuaverScreenType offset in QuaverGameplayScreen.cs on line 9 changed from 0xE8 to 0xF0.

**Comment by mrflashstudio** [comment]
Fixed in #18
