### ISSUE TITLE
net.core problem

### ISSUE THREAD

**Issue by gutzzzzxd** [mrflashstudio/Quack#22]
It says i didnt download net.core but i already did several times. how do i fix this
?

**Comment by NotNullified** [comment]
What version did you download?

**Comment by gutzzzzxd** [comment]
> What version did you download?

i downloaded the 3.1.20 one

**Comment by NotNullified** [comment]
Did you download the terminal or desktop version?

**Comment by gutzzzzxd** [comment]
> Did you download the terminal or desktop version?

the terminal one

**Comment by NotNullified** [comment]
Download the desktop one as well, then try again.
