### ISSUE TITLE
Need help with getting Quack to work!

### ISSUE THREAD

**Issue by uhSuy** [mrflashstudio/Quack#7]
Hello, so basically I downloaded Quack and below I will attach my folder to show you what it looks like for me (Am I missing something?)
Whenever I try to open Quack.exe the cmd window just flashes for a split second and nothing happens afterwards, could you please help me out with my issue?
![image](https://user-images.githubusercontent.com/70644495/91989083-5ea05380-ed30-11ea-9379-d2752bbc6ecd.png)

**Comment by mrflashstudio** [comment]
You probably don't have .net core 3.0 runtime installed, that's why it fails to launch.

**Comment by uhSuy** [comment]
Alright, this fixed my issue. Thanks for your quick response!
closing since issue is resolved
