### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by hikaruichiro** [mrflashstudio/Quack#8]
Can i have a full tutorial how this hack needs to open? i don't really know how it works,i don't know how and what program to use for it.

**Comment by mrflashstudio** [comment]
install .net core 3.0 runtime and reboot your pc. then go to the [latest release](https://github.com/mrflashstudio/Quack/releases/tag/1.0.0), download it and run Quack.exe

**Comment by hikaruichiro** [comment]
ok i will try that

**Comment by hikaruichiro** [comment]
@mrflashstudio you are a genius! is working,thank you!
