### ISSUE TITLE
Failed to Initialize

### ISSUE THREAD

**Issue by jahzaer** [mrflashstudio/Quack#9]
I have .net 3.0 and I tried running your release and also compiling it myself but I get this error both times

https://prnt.sc/wciywv

Also my OS info
https://prnt.sc/wciz5k

**Comment by jahzaer** [comment]
I am sorry if I wasted your time seems that even though I'm not playing valorant I need to uninstall the anticheat. I have valorant closed too I guess cause its kernel or something but this fixed it. Thanks anyways!!

**Comment by mrflashstudio** [comment]
Oh thanks for the info! Never thought this shitty anticheat could cause this.

**Comment by jahzaer** [comment]
Yeah well it worked once but when I closed it and tried opening it again today it presented the same error even with vanguard gone.
